version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    environment:
      API_KEY: 9b0a54d931f6c9e7710d4ab6
    healthcheck:
      test: curl http://localhost:8080/ || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
